### ISSUE TITLE
Remove mixin hotswapping tutorial

### ISSUE THREAD

**Issue by modmuss50** [FabricMC/fabric-docs#108]
This is an advanced feature that is not supported by all JVMs and is prone to error. I do plan on adding an option to loom to solve some of these issues. I dont think we should suggest for all users to set this when they are unlikely to ever use it.

**Comment by LlamaLad7** [comment]
It's a fairly commonly used feature, back when mixinextras caused a few issues with it I had many requests for it to be fixed. What JVMs doesn't it work on exactly? I've never had any issues with various Hotspot JVMs and almost no one uses OpenJ9.

**Comment by modmuss50** [comment]
> It's a fairly commonly used feature

I wasnt aware of that, if thats the case then making it easier to use should be a higher priortiy. I have personally never used it before :D

> JVMs doesn't it work on exactly

 Ss far as I know it doenst work on DCEVM/JBR. I would be happy to be wrong though.

**Comment by LlamaLad7** [comment]
It's incredibly useful for debugging and when set up correctly doesn't fail or cause any issues. I will test on JBR

**Comment by LlamaLad7** [comment]
Doesn't seem to work with `-XX:+AllowEnhancedClassRedefinition` on but otherwise is fine on JBR. I've always found DCEVM much more temperamental than Mixin hotswap so that by no means invalidates it.

**Comment by IMB11** [comment]
Yeah I'm gonna say no on this, Mixin hotswapping is extremely useful and easier to set up than DCEVM in the view of new mod developers.

**Comment by JR1811** [comment]
I can confirm, I use hotswaps on mixins pretty often too.
The only problem is that it's a bit annoying to set up. So explaining it in the docs saves me some time for sure.

**Comment by leo60228** [comment]
> Doesn't seem to work with `-XX:+AllowEnhancedClassRedefinition` on but otherwise is fine on JBR.

It works for me (I'm currently on JBR 21.0.3b465.3), though the added capabilities don't work for mixin classes.

**Comment by modmuss50** [comment]
I'll close this then, will still look to improve in loom.
