### ISSUE TITLE
Path to mineable tags is wrong in 1.21

### ISSUE THREAD

**Issue by Sirraide** [FabricMC/fabric-docs#131]
The path listed here
https://github.com/FabricMC/fabric-docs/blob/e037c312d7fab0ac3d94a1b7f2f7a9dfc7986191/develop/blocks/first-block.md?plain=1#L140-L142

doesn’t seem to be correct (anymore); at least in 1.21, the correct path seems to be `data/minecraft/tags/block/mineable/`, not `data/minecraft/tags/mineable/`.

**Comment by matthewperiut** [comment]
additionally there was a change from (1.20.6) loot_tables -> (1.21) loot_table in the file path for proper item/mob loot_table drops
