### ISSUE TITLE
Imports

### ISSUE THREAD

**Issue by home-gihub** [FabricMC/fabric-docs#142]
I followed the adding items guide.
I followed it and tried to test it out. (I got to the point of adding a name)
I got lots of errors so i had to search and it turns out I needed to import some things.

Same thing happend a load of times until:
```java
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemGroups;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;
import net.fabricmc.fabric.api.registry.*;
```

I had to import these and (as far as i know) there is no documentation.

**Comment by JaaiDead** [comment]
@home-gihub What is the error?

**Comment by IMB11** [comment]
> I had to import these and (as far as i know) there is no documentation.

This is basic Java knowledge, this is not an issue.
