### ISSUE TITLE
Remove deprecation in wiki for BlockEntityRenderers

### ISSUE THREAD

**Issue by tobiazsh** [FabricMC/fabric-docs#163]
The documentation for the Block Entity Renderers is using a deprecated method `BlockEntityRendererRegistry.register();` which was replaced by `BlockEntityRendererFactories.register();`
[Link to page](https://fabricmc.net/wiki/tutorial:blockentityrenderers)

**Comment by IMB11** [comment]
This repository is specifically for https://docs.fabricmc.net/, not https://fabricmc.net/wiki, report this on the #wiki channel on the Discord.
