### ISSUE TITLE
Cannot Select Japanese on a Page Where Japanese Should be Available

### ISSUE THREAD

**Issue by Shin-Emon** [FabricMC/fabric-docs#172]
[This page](https://docs.fabricmc.net/develop/getting-started/introduction-to-fabric-and-modding) is supposed to have a Japanese version, but I can't select Japanese from the drop-down menu.

**Comment by its-miroma** [comment]
You must translate [index.md](https://github.com/FabricMC/fabric-docs/tree/main/index.md) first. Once that's translated, Japanese will appear in the languages list
