### ISSUE TITLE
Link to crash report example results in error

### ISSUE THREAD

**Issue by woseK** [FabricMC/fabric-docs#188]
Clicking `this-crash-report` on `Crash reports` page results in 404 error ([link](https://docs.fabricmc.net/public/assets/players/crash-report-example.txt)).

![image](https://github.com/user-attachments/assets/185f8dde-ccee-4ddf-af62-4143e8df67b4)

The link works on a local build, but not on the docs.fabricnetmc.net site.
Changing 
`[this crash report](/public/assets/players/crash-report-example.txt)` 
to 
`[this crash report](/assets/players/crash-report-example.txt)`
solves this problem, but then clicking that link on GitHub doesn't redirect to the crash example.

**Comment by its-miroma** [comment]
> clicking that link on GitHub doesn't redirect to the crash example

That's intended behavior: images already do not work on GitHub.

---

If you want to open a simple PR, I'll merge it!
