### ISSUE TITLE
Dose not explain most errors

### ISSUE THREAD

**Issue by Cabbage698** [FabricMC/fabric-docs#197]
For some reason i cant figure out why i got this error "error: package jdk.internal.misc does not exist
import jdk.internal.misc.OSEnvironment;" And i dont understand how to fix it

**Comment by Cabbage698** [comment]
and no it wont let me launch the game

**Comment by its-miroma** [comment]
If this is related to the Fabric Documentation, please provide a link to the appropriate page, otherwise you may get help on the Fabric Discord Server.
