### ISSUE TITLE
develop/events#adding-items-to-the-loot-table uses `v2` instead of `v3`

### ISSUE THREAD

**Issue by EpicVon2468** [FabricMC/fabric-docs#199]
![image](https://github.com/user-attachments/assets/54cb995e-ad0c-4b90-8490-d5793655a7b8)
In the above image, the LootTableEvents.MODIFY.register() parameters do not match the actual parameters in the code. See below for the actual parameters.
![image](https://github.com/user-attachments/assets/e8d05f49-f8ad-46d8-bf75-ecf4dd22ed82)
(ignore my ugly theme)

**Comment by EpicVon2468** [comment]
(I forgot to link the exact page so https://docs.fabricmc.net/develop/events#adding-items-to-the-loot-table)

**Comment by its-miroma** [comment]
You're probably using `v3`, which needs `registries`, but `v2` (deprecated, but used in that file for some reason) does not.

Sources:
- v2: <https://maven.fabricmc.net/docs/fabric-api-0.106.0+1.21.1/net/fabricmc/fabric/api/loot/v2/LootTableEvents.html#MODIFY>
- v3: <https://maven.fabricmc.net/docs/fabric-api-0.106.0+1.21.1/net/fabricmc/fabric/api/loot/v3/LootTableEvents.html#MODIFY>

The question is: why are we using `v2`? @FabricMC/documentation
