### ISSUE TITLE
Creating Your First Item: Change "`interface` class" to "class implementing `interface`"

### ISSUE THREAD

**Issue by gboy800** [FabricMC/fabric-docs#217]
In the 1.21 docs on the Creating Your First Item page, in the subsection titled "Registering an Item", the example `ModInitializer` interface is consistently mislabeled as a class.

**Comment by Linguardium** [comment]
> call it from your ModInitializer class

it is not calling `ModInitializer` a class, its calling your class, that implements `ModInitializer`, a class.

**Comment by gboy800** [comment]
As quoted:
> To do this, you can add a public static initialize method to your class and call it from your `ModInitializer` **class**

The wording of the page seems a bit unclear. Maybe specify which class/interface is being referenced each time you mention "class"?

**Comment by gboy800** [comment]
Also, unless I am misremembering, aren't you only able to call `implements` on interfaces and `extends` on classes?

**Comment by Linguardium** [comment]
yes. and your class implements the interface. your class is a class.

**Comment by gboy800** [comment]
So, to be clear, `ModInitializer` is an interface within the Fabric API, not a class, despite the quote? I am genuinely quite confused, as apparently you call `initialize()` "from your `ModInitializer` **class**", which doesn't seem to line up with what you're actually supposed to do, namely:

Write a static dummy method in your `ModItems` class
Create a new class specifically to register said items, called `FabricDocsReferenceItems`, which implements the `ModInitializer` interface.
Do the general implements interface stuff and copy-paste the example code.

**Comment by Linguardium** [comment]
you make a class that implements ModInitializer (the official template generator does this for you)
inside that class, your class, your class that implements ModInitializer interface, is an onInitialize method. the onInitialize method is called when your mod is first initialized

inside your class, the class that is implementing the ModInitializer interface, you will call ModItem's initialize method. this ensures the ModItems class is loaded during your mod initialization.

ModItems is not implementing ModInitializer. that is not your ModInitializer implementing class.

**Comment by gboy800** [comment]
Yes, I agree, but the crux of the matter is that `ModInitializer` is labelled as a class, and specifically one that the reader themselves has written, as evidenced by "your `ModInitializer` class".

The tutorial for that section seems poorly written, as it:

1. calls `ModInitializer` a class
2. calls `ModInitializer` **your** class
3. doesn't correctly label which class should implement `ModInitializer`

The fact that you have to explain it to me is evidence of that

**Comment by Linguardium** [comment]
no, it was never labeled as a class.

it is using `ModInitializer` as a label to indicate your own class that adheres to the interface requirements and implements the interface. it is using shorthand instead of saying:
`Inside the method that you created that is implementing the ModInitializer interface`
it is saying
`inside your ModInitializer class` 
where `your` indicates that you created the class and control the code of it, and `ModInitializer` is the descriptor so you know which class of yours it is talking about

**Comment by Linguardium** [comment]
it is no different than saying "ride your red bicycle to the store". Red is not being called a bicycle

**Comment by gboy800** [comment]
I finally understand that `ModInitializer` here is the adjective and not the actual class, but perhaps still change it to a longer description? What you're essentially saying is "Your pet is brown" to someone with a red cat and a brown dog.

**Comment by gboy800** [comment]
To be clear, I'm not ragging on the tutorial. I just got heavily confused by what it was saying as somebody who's worked with Java for a while and is just starting Fabric.

**Comment by Linguardium** [comment]
its saying "touch your brown pet" and it is confusing you because brown is not a pet and your cat is red. I honestly dont see a confusion here. this is both common usage of descriptors in english and common usage of interface and parent class names to describe child/implementor classes

**Comment by gboy800** [comment]
"`ModInitializer` class" can stand for "the class called `ModInitializer`" too, as per english grammar, which is where my confusion began

**Comment by Linguardium** [comment]
ignoring parts of a sentence is not an english issue its a lack of attention to the things that are being read.

**Comment by gboy800** [comment]
Damn, no need to be rude. I'm just trying to point out that grammatically, the sentence is open to multiple interpretations and it's probably better to clarify a bit more rather than refer to shorthand.

**Comment by haykam821** [comment]
The class being referred to isn't `ModInitializer`, so I think calling it a `ModInitializer` class or interface would be wrong. Calling the class a `ModInitializer` implementation makes more sense to me, since that accurately describes the relationship between the class and `ModInitializer`.

**Comment by Earthcomputer** [comment]
It's the mod initializer class

**Comment by its-miroma** [comment]
I guess it may be confusing, we'll change it to something like "class implementing `ModInitializer`". We might also explain it once, then use the shorter form.

If you want to push a PR, you're welcome to, otherwise I'll do it myself.
