### ISSUE TITLE
Typo on the command arguments page

### ISSUE THREAD

**Issue by dabigf5** [FabricMC/fabric-docs#220]
https://docs.fabricmc.net/develop/commands/arguments
![image](https://github.com/user-attachments/assets/3f5deca0-535e-4ee6-ada8-84befbe34377)

**Comment by its-miroma** [comment]
Simple refactor in https://github.com/FabricMC/fabric-docs/blob/main/reference/latest/src/main/java/com/example/docs/command/FabricDocsReferenceCommands.java#L73:

```diff
-        private static int executeWithOneAre(CommandContext<ServerCommandSource> context) {
+        private static int executeWithOneArg(CommandContext<ServerCommandSource> context) {
```

Feel free to push a PR, or I'll do it once I'm on the PC.
