### ISSUE TITLE
Docs pages harder to follow than older wiki pages

### ISSUE THREAD

**Issue by Bowswa** [FabricMC/fabric-docs#221]
I am still very new to modding, and only made a couple basic blocks using the old wiki pages. It took me about 30 minutes to figure out how everything worked, and even go ahead and do a test boot with everything working. By the time i booted, i understood everything very clearly.

On the new docs pages, I am struggling. A lot. I've been here an hour, having done the ADHD drop the mod efforts, and forgotten everything from the last time. I also somehow lost my old mod haha. 

The main problem stumping me is what values am i supposed to replace with values specific to my mod? It was really clear on the wiki, but not so much on the docs. I don't understand what is going on, and can't make a working mod at this time. I would like this issue to be improved upon, but i will say the docs are looking great otherwise.

**Comment by its-miroma** [comment]
Thank you for your feedback.
We are considering some changes to class names (see issue #162) which may make code clearer. We also want to make it clear that a fully-working mod is available in this repository (tested and built successfully).
Please provide more precious feedback

**Comment by Bowswa** [comment]
I see the feedback provided in the other ticket, i think it might be considered replacing such values with "YOURMODID", and "YOURBLOCK", and "YOURINITCLASS" and such, making it even clearer than even the wiki was.

**Comment by its-miroma** [comment]
I guess I'll close this issue as a duplicate of 162

**Comment by its-miroma** [comment]
I guess I'll close this issue as a duplicate of #162

**Comment by its-miroma** [comment]
Duplicate of #162

**Comment by its-miroma** [comment]
Hi @Bowswa, we just merged #357 which should help with this, would you want to take a look at the docs once again?
