### ISSUE TITLE
Item Texture Will Not Load

### ISSUE THREAD

**Issue by Android789515** [FabricMC/fabric-docs#231]
I created a 16x16 png file correctly named in `assets/my_mod_id/textures/item`.

My lang file loads the name just fine.

1.21.4

![2024-12-15_23 29 47](https://github.com/user-attachments/assets/b2caedff-2790-4020-a101-aa57073e7b1a)

**Comment by Android789515** [comment]
Tried a different icon and still no texture.  Replaced both the model and texture files and their folders.  Still I have no texture.

**Comment by Linguardium** [comment]
the docs are not updated for 1.21.4 changes.

make a folder
assets/yourmodname/items
put a json file in it for your item
```
{
  "model": {
    "type": "minecraft:model",
    "model": "yourmod:item/youritemmodel"
  }
}
```
its basically the item state (like blockstate for items)
it replaced the overrides section in old models
```
{
  "model": {
    "type": "minecraft:model",
    "model": "minecraft:item/ender_pearl"
  }
}
```
a vanilla example in assets\minecraft\items\ender_pearl.json

These model providers are effectively like blockstates but for itemstacks, replacing the old override and modelpredicateprovider system

**Comment by Android789515** [comment]
> the docs are not updated for 1.21.4 changes.
> 
> make a folder assets/yourmodname/items put a json file in it for your item
> 
> ```
> {
>   "model": {
>     "type": "minecraft:model",
>     "model": "yourmod:item/youritemmodel"
>   }
> }
> ```
> 
> its basically the item state (like blockstate for items) it replaced the overrides section in old models
> 
> ```
> {
>   "model": {
>     "type": "minecraft:model",
>     "model": "minecraft:item/ender_pearl"
>   }
> }
> ```
> 
> a vanilla example in assets\minecraft\items\ender_pearl.json
> 
> These model providers are effectively like blockstates but for itemstacks, replacing the old override and modelpredicateprovider system

No luck.  Do I need to move my texture file as well?

**Comment by Linguardium** [comment]
no, this is in addition to your model and texture file

**Comment by Linguardium** [comment]
not really a docs issue. i suggest either going to the discord https://discord.gg/v6v4pMv or opening a discussion https://github.com/orgs/FabricMC/discussions

**Comment by Android789515** [comment]
> no, this is in addition to your model and texture file

Thank you.  I added my model back and I see my texture now.
