### ISSUE TITLE
Replace curseforge links with modrinth links (mainly the "Download Fabric API" link)

### ISSUE THREAD

**Issue by zndrmn** [FabricMC/fabric-docs#27]
Basically what the title says; replace curseforge links with modrinth links (mainly the "Download Fabric API" link)

![image](https://github.com/FabricMC/fabric-docs/assets/77690119/a81c6eec-2153-42f1-9ca3-11c4abd233e8)
![image](https://github.com/FabricMC/fabric-docs/assets/77690119/3837bc72-04b5-4662-8e53-fade2904e7df)

**Comment by IMB11** [comment]
This is the wrong repository, you should put this on https://github.com/FabricMC/fabricmc.net
