### ISSUE TITLE
Unable To Download

### ISSUE THREAD

**Issue by FeeshyHammy** [FabricMC/fabric-docs#93]
I have tried to download fabric, but I can't. It keeps saying "Virus Detected" but there is no information about it from my antivirus or the browser I am using. I don't know what is causing this, but it may have something to do with the fact that the file is a .exe. Do you have any ways to fix it?

**Comment by Boobies** [comment]
This is a bug tracker, not a place to get support. There are links to the Fabric Discord, where you can ask on the appropriate channel.

**Comment by modmuss50** [comment]
Unfortunately some anti-virus does detect the installer, this is a false positive and likely becuase we are unable to sign it. You can always use the universal .jar download instead.

👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
