### ISSUE TITLE
develop/commands/basics points to non-existing code

### ISSUE THREAD

**Issue by Boobies** [FabricMC/fabric-docs#94]
In the _Command Redirects_ section there is a code box that currently displays "No lines matched." because it doesn't point to any existing code. The code example should be something using `redirect` on one of the previously registered commands. There should also be a paragraph explaining that you don't necessarily need to redirect to the root node, like in the original wiki article.

**Comment by its-miroma** [comment]
Fixed by #148 (2 months ago!)
